spring.application.name=banckAccount

spring.datasource.url=jdbc:postgresql://localhost:5432/bank
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret-key=4f5c7a9e8d6b3c1a2f9e7d5c8b6a4f5c7a9e8d6b3c1a2f9e7d5c8b6a4f5c7a9
jwt.expiration=86400000